DROP TABLE IF EXISTS Medicamentos;
CREATE TABLE Medicamentos(
    id INT PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    TIPO_LABORATORIO VARCHAR(255) NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO DECIMAL NOT NULL
);